// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/appserver_role_sub/appserver_role_sub.proto

package appserverrolesub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppserverRoleSubService_Create_FullMethodName             = "/v1.appserverrolesub.AppserverRoleSubService/Create"
	AppserverRoleSubService_ListServerRoleSubs_FullMethodName = "/v1.appserverrolesub.AppserverRoleSubService/ListServerRoleSubs"
	AppserverRoleSubService_Delete_FullMethodName             = "/v1.appserverrolesub.AppserverRoleSubService/Delete"
)

// AppserverRoleSubServiceClient is the client API for AppserverRoleSubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppserverRoleSubServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	ListServerRoleSubs(ctx context.Context, in *ListServerRoleSubsRequest, opts ...grpc.CallOption) (*ListServerRoleSubsResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type appserverRoleSubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppserverRoleSubServiceClient(cc grpc.ClientConnInterface) AppserverRoleSubServiceClient {
	return &appserverRoleSubServiceClient{cc}
}

func (c *appserverRoleSubServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, AppserverRoleSubService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appserverRoleSubServiceClient) ListServerRoleSubs(ctx context.Context, in *ListServerRoleSubsRequest, opts ...grpc.CallOption) (*ListServerRoleSubsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServerRoleSubsResponse)
	err := c.cc.Invoke(ctx, AppserverRoleSubService_ListServerRoleSubs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appserverRoleSubServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, AppserverRoleSubService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppserverRoleSubServiceServer is the server API for AppserverRoleSubService service.
// All implementations must embed UnimplementedAppserverRoleSubServiceServer
// for forward compatibility.
type AppserverRoleSubServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	ListServerRoleSubs(context.Context, *ListServerRoleSubsRequest) (*ListServerRoleSubsResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedAppserverRoleSubServiceServer()
}

// UnimplementedAppserverRoleSubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppserverRoleSubServiceServer struct{}

func (UnimplementedAppserverRoleSubServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAppserverRoleSubServiceServer) ListServerRoleSubs(context.Context, *ListServerRoleSubsRequest) (*ListServerRoleSubsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServerRoleSubs not implemented")
}
func (UnimplementedAppserverRoleSubServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAppserverRoleSubServiceServer) mustEmbedUnimplementedAppserverRoleSubServiceServer() {
}
func (UnimplementedAppserverRoleSubServiceServer) testEmbeddedByValue() {}

// UnsafeAppserverRoleSubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppserverRoleSubServiceServer will
// result in compilation errors.
type UnsafeAppserverRoleSubServiceServer interface {
	mustEmbedUnimplementedAppserverRoleSubServiceServer()
}

func RegisterAppserverRoleSubServiceServer(s grpc.ServiceRegistrar, srv AppserverRoleSubServiceServer) {
	// If the following call pancis, it indicates UnimplementedAppserverRoleSubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppserverRoleSubService_ServiceDesc, srv)
}

func _AppserverRoleSubService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppserverRoleSubServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppserverRoleSubService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppserverRoleSubServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppserverRoleSubService_ListServerRoleSubs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServerRoleSubsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppserverRoleSubServiceServer).ListServerRoleSubs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppserverRoleSubService_ListServerRoleSubs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppserverRoleSubServiceServer).ListServerRoleSubs(ctx, req.(*ListServerRoleSubsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppserverRoleSubService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppserverRoleSubServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppserverRoleSubService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppserverRoleSubServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppserverRoleSubService_ServiceDesc is the grpc.ServiceDesc for AppserverRoleSubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppserverRoleSubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.appserverrolesub.AppserverRoleSubService",
	HandlerType: (*AppserverRoleSubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AppserverRoleSubService_Create_Handler,
		},
		{
			MethodName: "ListServerRoleSubs",
			Handler:    _AppserverRoleSubService_ListServerRoleSubs_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AppserverRoleSubService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/appserver_role_sub/appserver_role_sub.proto",
}
