version: "3.8"

services:
  mist-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PORT: ${APP_PORT}

        REDIS_HOSTNAME: ${REDIS_HOSTNAME}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_USERNAME: ${REDIS_USERNAME}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        REDIS_DB: ${DATABASE_NAME}
        REDIS_NOTIFICATION_CHANNEL: ${REDIS_NOTIFICATION_CHANNEL}

        LOG_LEVEL: ${LOG_LEVEL}

        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_ROLE: ${DATABASE_ROLE}

        MIST_API_JWT_SECRET_KEY: ${MIST_API_JWT_SECRET_KEY}
        MIST_API_JWT_AUDIENCE: ${MIST_API_JWT_AUDIENCE}
        MIST_API_JWT_ISSUER: ${MIST_API_JWT_ISSUER}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      APP_PORT: ${APP_PORT}

      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      REDIS_NOTIFICATION_CHANNEL: ${REDIS_NOTIFICATION_CHANNEL}

      LOG_LEVEL: ${LOG_LEVEL}

      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_ROLE: ${DATABASE_ROLE}

      MIST_API_JWT_SECRET_KEY: ${MIST_API_JWT_SECRET_KEY}
      MIST_API_JWT_AUDIENCE: ${MIST_API_JWT_AUDIENCE}
      MIST_API_JWT_ISSUER: ${MIST_API_JWT_ISSUER}

