// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/appserver_role/appserver_role.proto

package appserverrole

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppserverRoleService_CreateAppserverRole_FullMethodName  = "/v1.appserverrole.AppserverRoleService/CreateAppserverRole"
	AppserverRoleService_GetAllAppserverRoles_FullMethodName = "/v1.appserverrole.AppserverRoleService/GetAllAppserverRoles"
	AppserverRoleService_DeleteAppserverRole_FullMethodName  = "/v1.appserverrole.AppserverRoleService/DeleteAppserverRole"
)

// AppserverRoleServiceClient is the client API for AppserverRoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppserverRoleServiceClient interface {
	CreateAppserverRole(ctx context.Context, in *CreateAppserverRoleRequest, opts ...grpc.CallOption) (*CreateAppserverRoleResponse, error)
	GetAllAppserverRoles(ctx context.Context, in *GetAllAppserverRolesRequest, opts ...grpc.CallOption) (*GetAllAppserverRolesResponse, error)
	DeleteAppserverRole(ctx context.Context, in *DeleteAppserverRoleRequest, opts ...grpc.CallOption) (*DeleteAppserverRoleResponse, error)
}

type appserverRoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppserverRoleServiceClient(cc grpc.ClientConnInterface) AppserverRoleServiceClient {
	return &appserverRoleServiceClient{cc}
}

func (c *appserverRoleServiceClient) CreateAppserverRole(ctx context.Context, in *CreateAppserverRoleRequest, opts ...grpc.CallOption) (*CreateAppserverRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAppserverRoleResponse)
	err := c.cc.Invoke(ctx, AppserverRoleService_CreateAppserverRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appserverRoleServiceClient) GetAllAppserverRoles(ctx context.Context, in *GetAllAppserverRolesRequest, opts ...grpc.CallOption) (*GetAllAppserverRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllAppserverRolesResponse)
	err := c.cc.Invoke(ctx, AppserverRoleService_GetAllAppserverRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appserverRoleServiceClient) DeleteAppserverRole(ctx context.Context, in *DeleteAppserverRoleRequest, opts ...grpc.CallOption) (*DeleteAppserverRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAppserverRoleResponse)
	err := c.cc.Invoke(ctx, AppserverRoleService_DeleteAppserverRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppserverRoleServiceServer is the server API for AppserverRoleService service.
// All implementations must embed UnimplementedAppserverRoleServiceServer
// for forward compatibility.
type AppserverRoleServiceServer interface {
	CreateAppserverRole(context.Context, *CreateAppserverRoleRequest) (*CreateAppserverRoleResponse, error)
	GetAllAppserverRoles(context.Context, *GetAllAppserverRolesRequest) (*GetAllAppserverRolesResponse, error)
	DeleteAppserverRole(context.Context, *DeleteAppserverRoleRequest) (*DeleteAppserverRoleResponse, error)
	mustEmbedUnimplementedAppserverRoleServiceServer()
}

// UnimplementedAppserverRoleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppserverRoleServiceServer struct{}

func (UnimplementedAppserverRoleServiceServer) CreateAppserverRole(context.Context, *CreateAppserverRoleRequest) (*CreateAppserverRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAppserverRole not implemented")
}
func (UnimplementedAppserverRoleServiceServer) GetAllAppserverRoles(context.Context, *GetAllAppserverRolesRequest) (*GetAllAppserverRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllAppserverRoles not implemented")
}
func (UnimplementedAppserverRoleServiceServer) DeleteAppserverRole(context.Context, *DeleteAppserverRoleRequest) (*DeleteAppserverRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAppserverRole not implemented")
}
func (UnimplementedAppserverRoleServiceServer) mustEmbedUnimplementedAppserverRoleServiceServer() {}
func (UnimplementedAppserverRoleServiceServer) testEmbeddedByValue()                              {}

// UnsafeAppserverRoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppserverRoleServiceServer will
// result in compilation errors.
type UnsafeAppserverRoleServiceServer interface {
	mustEmbedUnimplementedAppserverRoleServiceServer()
}

func RegisterAppserverRoleServiceServer(s grpc.ServiceRegistrar, srv AppserverRoleServiceServer) {
	// If the following call pancis, it indicates UnimplementedAppserverRoleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppserverRoleService_ServiceDesc, srv)
}

func _AppserverRoleService_CreateAppserverRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppserverRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppserverRoleServiceServer).CreateAppserverRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppserverRoleService_CreateAppserverRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppserverRoleServiceServer).CreateAppserverRole(ctx, req.(*CreateAppserverRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppserverRoleService_GetAllAppserverRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllAppserverRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppserverRoleServiceServer).GetAllAppserverRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppserverRoleService_GetAllAppserverRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppserverRoleServiceServer).GetAllAppserverRoles(ctx, req.(*GetAllAppserverRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppserverRoleService_DeleteAppserverRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAppserverRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppserverRoleServiceServer).DeleteAppserverRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppserverRoleService_DeleteAppserverRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppserverRoleServiceServer).DeleteAppserverRole(ctx, req.(*DeleteAppserverRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppserverRoleService_ServiceDesc is the grpc.ServiceDesc for AppserverRoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppserverRoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.appserverrole.AppserverRoleService",
	HandlerType: (*AppserverRoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAppserverRole",
			Handler:    _AppserverRoleService_CreateAppserverRole_Handler,
		},
		{
			MethodName: "GetAllAppserverRoles",
			Handler:    _AppserverRoleService_GetAllAppserverRoles_Handler,
		},
		{
			MethodName: "DeleteAppserverRole",
			Handler:    _AppserverRoleService_DeleteAppserverRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/appserver_role/appserver_role.proto",
}
