// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: appserver_role_sub.sql

package qx

import (
	"context"

	"github.com/google/uuid"
)

const createAppserverRoleSub = `-- name: CreateAppserverRoleSub :one
INSERT INTO appserver_role_sub (
  appserver_sub_id,
  appserver_role_id,
  appuser_id,
  appserver_id
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, appuser_id, appserver_sub_id, appserver_role_id, appserver_id, created_at, updated_at
`

type CreateAppserverRoleSubParams struct {
	AppserverSubID  uuid.UUID
	AppserverRoleID uuid.UUID
	AppuserID       uuid.UUID
	AppserverID     uuid.UUID
}

func (q *Queries) CreateAppserverRoleSub(ctx context.Context, arg CreateAppserverRoleSubParams) (AppserverRoleSub, error) {
	row := q.db.QueryRow(ctx, createAppserverRoleSub,
		arg.AppserverSubID,
		arg.AppserverRoleID,
		arg.AppuserID,
		arg.AppserverID,
	)
	var i AppserverRoleSub
	err := row.Scan(
		&i.ID,
		&i.AppuserID,
		&i.AppserverSubID,
		&i.AppserverRoleID,
		&i.AppserverID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAppserverRoleSub = `-- name: DeleteAppserverRoleSub :execrows
DELETE FROM appserver_role_sub AS role_sub
USING appserver AS a, appserver_role AS ar
WHERE a.id=ar.appserver_id
  AND ar.id=role_sub.appserver_role_id
  AND role_sub.id=$1
  AND a.appuser_id=$2
`

type DeleteAppserverRoleSubParams struct {
	ID        uuid.UUID
	AppuserID uuid.UUID
}

func (q *Queries) DeleteAppserverRoleSub(ctx context.Context, arg DeleteAppserverRoleSubParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAppserverRoleSub, arg.ID, arg.AppuserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAppserverRoleSubById = `-- name: GetAppserverRoleSubById :one
SELECT id, appuser_id, appserver_sub_id, appserver_role_id, appserver_id, created_at, updated_at
FROM appserver_role_sub
WHERE id=$1
LIMIT 1
`

func (q *Queries) GetAppserverRoleSubById(ctx context.Context, id uuid.UUID) (AppserverRoleSub, error) {
	row := q.db.QueryRow(ctx, getAppserverRoleSubById, id)
	var i AppserverRoleSub
	err := row.Scan(
		&i.ID,
		&i.AppuserID,
		&i.AppserverSubID,
		&i.AppserverRoleID,
		&i.AppserverID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppuserRoleSubs = `-- name: ListAppuserRoleSubs :many
SELECT
  role_sub.id,
  role_sub.appuser_id,
  role_sub.appserver_role_id,
  role_sub.appserver_id
FROM appserver_role_sub AS role_sub
WHERE role_sub.appuser_id=$1
  AND role_sub.appserver_id=$2
`

type ListAppuserRoleSubsParams struct {
	AppuserID   uuid.UUID
	AppserverID uuid.UUID
}

type ListAppuserRoleSubsRow struct {
	ID              uuid.UUID
	AppuserID       uuid.UUID
	AppserverRoleID uuid.UUID
	AppserverID     uuid.UUID
}

func (q *Queries) ListAppuserRoleSubs(ctx context.Context, arg ListAppuserRoleSubsParams) ([]ListAppuserRoleSubsRow, error) {
	rows, err := q.db.Query(ctx, listAppuserRoleSubs, arg.AppuserID, arg.AppserverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppuserRoleSubsRow
	for rows.Next() {
		var i ListAppuserRoleSubsRow
		if err := rows.Scan(
			&i.ID,
			&i.AppuserID,
			&i.AppserverRoleID,
			&i.AppserverID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServerRoleSubs = `-- name: ListServerRoleSubs :many
SELECT
  role_sub.id,
  role_sub.appuser_id,
  role_sub.appserver_role_id,
  role_sub.appserver_id

FROM appserver_role_sub AS role_sub
WHERE role_sub.appserver_id=$1
`

type ListServerRoleSubsRow struct {
	ID              uuid.UUID
	AppuserID       uuid.UUID
	AppserverRoleID uuid.UUID
	AppserverID     uuid.UUID
}

func (q *Queries) ListServerRoleSubs(ctx context.Context, appserverID uuid.UUID) ([]ListServerRoleSubsRow, error) {
	rows, err := q.db.Query(ctx, listServerRoleSubs, appserverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServerRoleSubsRow
	for rows.Next() {
		var i ListServerRoleSubsRow
		if err := rows.Scan(
			&i.ID,
			&i.AppuserID,
			&i.AppserverRoleID,
			&i.AppserverID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
