// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: appserver_role.sql

package qx

import (
	"context"

	"github.com/google/uuid"
)

const createAppserverRole = `-- name: CreateAppserverRole :one
INSERT INTO appserver_role (
  appserver_id,
  name
) VALUES (
  $1,
  $2
)
RETURNING id, appserver_id, name, created_at, updated_at
`

type CreateAppserverRoleParams struct {
	AppserverID uuid.UUID
	Name        string
}

func (q *Queries) CreateAppserverRole(ctx context.Context, arg CreateAppserverRoleParams) (AppserverRole, error) {
	row := q.db.QueryRow(ctx, createAppserverRole, arg.AppserverID, arg.Name)
	var i AppserverRole
	err := row.Scan(
		&i.ID,
		&i.AppserverID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAppserverRole = `-- name: DeleteAppserverRole :execrows
DELETE FROM appserver_role as ar
WHERE ar.id=$1
`

func (q *Queries) DeleteAppserverRole(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAppserverRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAppserverRoleById = `-- name: GetAppserverRoleById :one
SELECT id, appserver_id, name, created_at, updated_at
FROM appserver_role
WHERE id=$1
LIMIT 1
`

func (q *Queries) GetAppserverRoleById(ctx context.Context, id uuid.UUID) (AppserverRole, error) {
	row := q.db.QueryRow(ctx, getAppserverRoleById, id)
	var i AppserverRole
	err := row.Scan(
		&i.ID,
		&i.AppserverID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppserverRoles = `-- name: ListAppserverRoles :many
SELECT id, appserver_id, name, created_at, updated_at
FROM appserver_role
WHERE appserver_id=$1
`

func (q *Queries) ListAppserverRoles(ctx context.Context, appserverID uuid.UUID) ([]AppserverRole, error) {
	rows, err := q.db.Query(ctx, listAppserverRoles, appserverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppserverRole
	for rows.Next() {
		var i AppserverRole
		if err := rows.Scan(
			&i.ID,
			&i.AppserverID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
