// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: channel.sql

package qx

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channel (
  name,
  appserver_id,
  is_private
) VALUES (
  $1,
  $2,
  $3
)
RETURNING id, name, appserver_id, is_private, created_at, updated_at
`

type CreateChannelParams struct {
	Name        string
	AppserverID uuid.UUID
	IsPrivate   bool
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel, arg.Name, arg.AppserverID, arg.IsPrivate)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AppserverID,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE FROM channel
WHERE id=$1
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const filterChannel = `-- name: FilterChannel :many
SELECT id, name, appserver_id, is_private, created_at, updated_at
FROM channel
WHERE appserver_id = COALESCE($1, appserver_id)
  AND is_private = COALESCE($2, is_private)
`

type FilterChannelParams struct {
	AppserverID pgtype.UUID
	IsPrivate   pgtype.Bool
}

func (q *Queries) FilterChannel(ctx context.Context, arg FilterChannelParams) ([]Channel, error) {
	rows, err := q.db.Query(ctx, filterChannel, arg.AppserverID, arg.IsPrivate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AppserverID,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelById = `-- name: GetChannelById :one
SELECT id, name, appserver_id, is_private, created_at, updated_at
FROM channel
WHERE id=$1
LIMIT 1
`

func (q *Queries) GetChannelById(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelById, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AppserverID,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelUsersByRoles = `-- name: GetChannelUsersByRoles :many
SELECT DISTINCT appuser.id, appuser.username, appuser.online_status, appuser.created_at, appuser.updated_at
FROM appuser
JOIN appserver_role_sub ON appserver_role_sub.appuser_id = appuser.id
JOIN channel_role ON channel_role.appserver_role_id = appserver_role_sub.app_server_role_id
WHERE channel_role.appserver_role_id = ANY($1::uuid[])
`

func (q *Queries) GetChannelUsersByRoles(ctx context.Context, dollar_1 []uuid.UUID) ([]Appuser, error) {
	rows, err := q.db.Query(ctx, getChannelUsersByRoles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appuser
	for rows.Next() {
		var i Appuser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.OnlineStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelsForUser = `-- name: GetChannelsForUser :many
SELECT DISTINCT channel.id, channel.name, channel.appserver_id, channel.is_private, channel.created_at, channel.updated_at
FROM channel
LEFT JOIN channel_role ON channel_role.channel_id = channel.id
LEFT JOIN appserver_role_sub ON appserver_role_sub.app_server_role_id = channel_role.appserver_role_id
WHERE channel.appserver_id = $2
  AND (
    channel_role.id IS NULL -- channels with no roles
    OR appserver_role_sub.appuser_id = $1 -- channels where user has a role
  )
`

type GetChannelsForUserParams struct {
	AppuserID   uuid.UUID
	AppserverID uuid.UUID
}

func (q *Queries) GetChannelsForUser(ctx context.Context, arg GetChannelsForUserParams) ([]Channel, error) {
	rows, err := q.db.Query(ctx, getChannelsForUser, arg.AppuserID, arg.AppserverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AppserverID,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServerChannels = `-- name: ListServerChannels :many
SELECT id, name, appserver_id, is_private, created_at, updated_at
FROM channel
WHERE name=COALESCE($2, name)
  AND appserver_id=$1
`

type ListServerChannelsParams struct {
	AppserverID uuid.UUID
	Name        pgtype.Text
}

func (q *Queries) ListServerChannels(ctx context.Context, arg ListServerChannelsParams) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listServerChannels, arg.AppserverID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AppserverID,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
