// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package qx

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Appserver struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Channel struct {
	ID          uuid.UUID
	Name        string
	AppserverID uuid.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}
