// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package qx

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAppserver(ctx context.Context, arg CreateAppserverParams) (Appserver, error)
	CreateAppserverPermission(ctx context.Context, arg CreateAppserverPermissionParams) (AppserverPermission, error)
	CreateAppserverRole(ctx context.Context, arg CreateAppserverRoleParams) (AppserverRole, error)
	CreateAppserverRoleSub(ctx context.Context, arg CreateAppserverRoleSubParams) (AppserverRoleSub, error)
	CreateAppserverSub(ctx context.Context, arg CreateAppserverSubParams) (AppserverSub, error)
	CreateAppuser(ctx context.Context, arg CreateAppuserParams) (Appuser, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateChannelPermission(ctx context.Context, arg CreateChannelPermissionParams) (ChannelPermission, error)
	CreateChannelRole(ctx context.Context, arg CreateChannelRoleParams) (ChannelRole, error)
	DeleteAppserver(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteAppserverPermission(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteAppserverRole(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteAppserverRoleSub(ctx context.Context, arg DeleteAppserverRoleSubParams) (int64, error)
	DeleteAppserverSub(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteChannel(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteChannelPermission(ctx context.Context, id uuid.UUID) (int64, error)
	// ...existing code...
	DeleteChannelRole(ctx context.Context, id uuid.UUID) (int64, error)
	FilterAppserverSub(ctx context.Context, arg FilterAppserverSubParams) ([]FilterAppserverSubRow, error)
	FilterChannelRole(ctx context.Context, arg FilterChannelRoleParams) ([]FilterChannelRoleRow, error)
	GetAppserverById(ctx context.Context, id uuid.UUID) (Appserver, error)
	GetAppserverPermissionById(ctx context.Context, id uuid.UUID) (AppserverPermission, error)
	GetAppserverPermissionForUser(ctx context.Context, arg GetAppserverPermissionForUserParams) (AppserverPermission, error)
	GetAppserverRoleById(ctx context.Context, id uuid.UUID) (AppserverRole, error)
	GetAppserverRoleSubById(ctx context.Context, id uuid.UUID) (AppserverRoleSub, error)
	GetAppserverSubById(ctx context.Context, id uuid.UUID) (AppserverSub, error)
	GetAppuserById(ctx context.Context, id uuid.UUID) (Appuser, error)
	GetAppuserRoles(ctx context.Context, arg GetAppuserRolesParams) ([]GetAppuserRolesRow, error)
	GetChannelById(ctx context.Context, id uuid.UUID) (Channel, error)
	GetChannelPermissionById(ctx context.Context, id uuid.UUID) (ChannelPermission, error)
	GetChannelRoleById(ctx context.Context, id uuid.UUID) (ChannelRole, error)
	GetChannelUsersByRoles(ctx context.Context, dollar_1 []uuid.UUID) ([]Appuser, error)
	GetChannelsForUser(ctx context.Context, arg GetChannelsForUserParams) ([]Channel, error)
	ListAppserverPermissions(ctx context.Context, appserverID uuid.UUID) ([]AppserverPermission, error)
	ListAppserverRoles(ctx context.Context, appserverID uuid.UUID) ([]AppserverRole, error)
	ListAppserverUserSubs(ctx context.Context, appserverID uuid.UUID) ([]ListAppserverUserSubsRow, error)
	ListAppservers(ctx context.Context, arg ListAppserversParams) ([]Appserver, error)
	ListChannelPermissions(ctx context.Context, channelID uuid.UUID) ([]ChannelPermission, error)
	ListChannelRoles(ctx context.Context, channelID uuid.UUID) ([]ChannelRole, error)
	ListServerChannels(ctx context.Context, arg ListServerChannelsParams) ([]Channel, error)
	ListServerRoleSubs(ctx context.Context, appserverID uuid.UUID) ([]ListServerRoleSubsRow, error)
	ListUserServerSubs(ctx context.Context, appuserID uuid.UUID) ([]ListUserServerSubsRow, error)
}

var _ Querier = (*Queries)(nil)
