// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package qx

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAppserver(ctx context.Context, arg CreateAppserverParams) (Appserver, error)
	CreateAppserverRole(ctx context.Context, arg CreateAppserverRoleParams) (AppserverRole, error)
	CreateAppserverRoleSub(ctx context.Context, arg CreateAppserverRoleSubParams) (AppserverRoleSub, error)
	CreateAppserverSub(ctx context.Context, arg CreateAppserverSubParams) (AppserverSub, error)
	CreateAppuser(ctx context.Context, arg CreateAppuserParams) (Appuser, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateChannelRole(ctx context.Context, arg CreateChannelRoleParams) (ChannelRole, error)
	DeleteAppserver(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteAppserverRole(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteAppserverRoleSub(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteAppserverSub(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteChannel(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteChannelRole(ctx context.Context, id uuid.UUID) (int64, error)
	FilterAppserverRoleSub(ctx context.Context, arg FilterAppserverRoleSubParams) ([]FilterAppserverRoleSubRow, error)
	FilterAppserverSub(ctx context.Context, arg FilterAppserverSubParams) ([]FilterAppserverSubRow, error)
	FilterChannel(ctx context.Context, arg FilterChannelParams) ([]Channel, error)
	FilterChannelRole(ctx context.Context, arg FilterChannelRoleParams) ([]FilterChannelRoleRow, error)
	GetAppserverById(ctx context.Context, id uuid.UUID) (Appserver, error)
	GetAppserverRoleById(ctx context.Context, id uuid.UUID) (AppserverRole, error)
	GetAppserverRoleSubById(ctx context.Context, id uuid.UUID) (AppserverRoleSub, error)
	GetAppserverSubById(ctx context.Context, id uuid.UUID) (AppserverSub, error)
	GetAppuserById(ctx context.Context, id uuid.UUID) (Appuser, error)
	GetAppuserRoles(ctx context.Context, arg GetAppuserRolesParams) ([]GetAppuserRolesRow, error)
	GetAppusersWithOnlySpecifiedRole(ctx context.Context, appserverRoleID uuid.UUID) ([]Appuser, error)
	GetChannelById(ctx context.Context, id uuid.UUID) (Channel, error)
	GetChannelRoleById(ctx context.Context, id uuid.UUID) (ChannelRole, error)
	GetChannelUsersByRoles(ctx context.Context, dollar_1 []uuid.UUID) ([]Appuser, error)
	GetChannelsForUsers(ctx context.Context, arg GetChannelsForUsersParams) ([]GetChannelsForUsersRow, error)
	GetChannelsIdIn(ctx context.Context, dollar_1 []uuid.UUID) ([]Channel, error)
	ListAppserverRoles(ctx context.Context, appserverID uuid.UUID) ([]AppserverRole, error)
	ListAppserverUserSubs(ctx context.Context, appserverID uuid.UUID) ([]ListAppserverUserSubsRow, error)
	ListAppservers(ctx context.Context, arg ListAppserversParams) ([]Appserver, error)
	ListChannelRoles(ctx context.Context, channelID uuid.UUID) ([]ChannelRole, error)
	ListServerChannels(ctx context.Context, arg ListServerChannelsParams) ([]Channel, error)
	ListServerRoleSubs(ctx context.Context, appserverID uuid.UUID) ([]ListServerRoleSubsRow, error)
	ListUserServerSubs(ctx context.Context, appuserID uuid.UUID) ([]ListUserServerSubsRow, error)
}

var _ Querier = (*Queries)(nil)
