- name: Run Hello World
  hosts: mist-docker-dev

  tasks:
    - name: Pull a specific Docker image
      community.docker.docker_image:
        name: "ubuntu"
        tag: "latest"
        source: "pull"
