when:
  - event: manual

steps:
  - name: Fetch and Initialize Credentials
    when:
      - evaluate: 'DEPLOY_DEV == "true"'
    image: registry.mist-project.app/mist-shared/alpine-ci:latest
    environment:
      OP_SERVICE_ACCOUNT_TOKEN:
        from_secret: OP_TOKEN
      OP_VAULT:
        from_secret: OP_VAULT
      TENANT_ACCOUNT_ID: "4wccsugzybkttewdtm2zujm5gu"
      BACKEND_ACCOUNT_ID: "a4gqxmodtuquf5w5r4iuxbmxg4"

    commands:
      - chmod +x helpers/fetch_creds_op.sh
      - ./helpers/fetch_creds_op.sh

  - name: Build Image and Push to Registry
    when:
      - evaluate: 'MANUAL_DEPLOY == "true"'
    image: woodpeckerci/plugin-kaniko
    privileged: true

    settings:
      repo: mist-backend
      dockerfile: Dockerfile
      tags:
        - latest # TODO: Add version tag or commit sha for incremental versions
      registry: registry.mist-project.app
      log-level: debug

  - name: Pull latest image in tenant
    when:
      - evaluate: 'MANUAL_DEPLOY == "true"'
    image: registry.mist-project.app/mist-shared/alpine-ci:latest
    environment:
      ANSIBLE_HOST_KEY_CHECKING: False
    commands:
      - source .tmpenvs
      - |
        ansible-playbook -i ansible/inventory/hosts.ini \
          ansible/playbooks/deploy.yml \
          --extra-vars "ansible_ssh_private_key_file=key.pem" \
          --extra-vars "ansible_user=$TENANT_USERNAME" \
          --extra-vars "LOG_LEVEL=$LOG_LEVEL" \
          --extra-vars "REDIS_HOSTNAME=$REDIS_HOSTNAME" \
          --extra-vars "REDIS_PORT=$REDIS_PORT" \
          --extra-vars "REDIS_USERNAME=$REDIS_USERNAME" \
          --extra-vars "REDIS_PASSWORD=$REDIS_PASSWORD" \
          --extra-vars "REDIS_DB=$REDIS_DB" \
          --extra-vars "REDIS_NOTIFICATION_CHANNEL=$REDIS_NOTIFICATION_CHANNEL" \
          --extra-vars "DATABASE_URL=$DATABASE_URL" \
          --extra-vars "MIST_API_JWT_SECRET_KEY=$MIST_API_JWT_SECRET_KEY" \
          --extra-vars "MIST_API_JWT_AUDIENCE=$MIST_API_JWT_AUDIENCE" \
          --extra-vars "MIST_API_JWT_ISSUER=$MIST_API_JWT_ISSUER" \
          --extra-vars "APP_PORT=$APP_PORT" \
