when:
  - event: manual

steps:
  - name: Build the image
    image: woodpeckerci/plugin-docker-buildx:6.0.2
    privileged: true

    settings:
      repo: mist-backend
      dockerfile: Dockerfile

      tags:
        - latest
      registry: registry.mist-project.app
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD

      debug: true
