when:
  - event: manual

steps:
  - name: Build the image
    image: woodpeckerci/plugin-docker-buildx:6.0.2
    privileged: true

    settings:
      repo: mist-project/mist-backend
      dockerfile: Dockerfile

      registry: registry.mist-project.app
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
