// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: mistbe/v1/mistbe.proto

package mistbe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----- SERVER -----
type Appserver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Appserver) Reset() {
	*x = Appserver{}
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appserver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appserver) ProtoMessage() {}

func (x *Appserver) ProtoReflect() protoreflect.Message {
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appserver.ProtoReflect.Descriptor instead.
func (*Appserver) Descriptor() ([]byte, []int) {
	return file_mistbe_v1_mistbe_proto_rawDescGZIP(), []int{0}
}

func (x *Appserver) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Appserver) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Appserver) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAppserverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppserverRequest) Reset() {
	*x = CreateAppserverRequest{}
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppserverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppserverRequest) ProtoMessage() {}

func (x *CreateAppserverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppserverRequest.ProtoReflect.Descriptor instead.
func (*CreateAppserverRequest) Descriptor() ([]byte, []int) {
	return file_mistbe_v1_mistbe_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAppserverRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetByIdAppserverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdAppserverRequest) Reset() {
	*x = GetByIdAppserverRequest{}
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdAppserverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdAppserverRequest) ProtoMessage() {}

func (x *GetByIdAppserverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdAppserverRequest.ProtoReflect.Descriptor instead.
func (*GetByIdAppserverRequest) Descriptor() ([]byte, []int) {
	return file_mistbe_v1_mistbe_proto_rawDescGZIP(), []int{2}
}

func (x *GetByIdAppserverRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAppserversRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppserversRequest) Reset() {
	*x = ListAppserversRequest{}
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppserversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppserversRequest) ProtoMessage() {}

func (x *ListAppserversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppserversRequest.ProtoReflect.Descriptor instead.
func (*ListAppserversRequest) Descriptor() ([]byte, []int) {
	return file_mistbe_v1_mistbe_proto_rawDescGZIP(), []int{3}
}

func (x *ListAppserversRequest) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

type DeleteAppserverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppserverRequest) Reset() {
	*x = DeleteAppserverRequest{}
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppserverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppserverRequest) ProtoMessage() {}

func (x *DeleteAppserverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppserverRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppserverRequest) Descriptor() ([]byte, []int) {
	return file_mistbe_v1_mistbe_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAppserverRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateAppserverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appserver     *Appserver             `protobuf:"bytes,1,opt,name=appserver,proto3" json:"appserver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppserverResponse) Reset() {
	*x = CreateAppserverResponse{}
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppserverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppserverResponse) ProtoMessage() {}

func (x *CreateAppserverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppserverResponse.ProtoReflect.Descriptor instead.
func (*CreateAppserverResponse) Descriptor() ([]byte, []int) {
	return file_mistbe_v1_mistbe_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAppserverResponse) GetAppserver() *Appserver {
	if x != nil {
		return x.Appserver
	}
	return nil
}

type GetByIdAppserverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appserver     *Appserver             `protobuf:"bytes,1,opt,name=appserver,proto3" json:"appserver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdAppserverResponse) Reset() {
	*x = GetByIdAppserverResponse{}
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdAppserverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdAppserverResponse) ProtoMessage() {}

func (x *GetByIdAppserverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdAppserverResponse.ProtoReflect.Descriptor instead.
func (*GetByIdAppserverResponse) Descriptor() ([]byte, []int) {
	return file_mistbe_v1_mistbe_proto_rawDescGZIP(), []int{6}
}

func (x *GetByIdAppserverResponse) GetAppserver() *Appserver {
	if x != nil {
		return x.Appserver
	}
	return nil
}

type ListAppserversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appservers    []*Appserver           `protobuf:"bytes,1,rep,name=appservers,proto3" json:"appservers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppserversResponse) Reset() {
	*x = ListAppserversResponse{}
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppserversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppserversResponse) ProtoMessage() {}

func (x *ListAppserversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppserversResponse.ProtoReflect.Descriptor instead.
func (*ListAppserversResponse) Descriptor() ([]byte, []int) {
	return file_mistbe_v1_mistbe_proto_rawDescGZIP(), []int{7}
}

func (x *ListAppserversResponse) GetAppservers() []*Appserver {
	if x != nil {
		return x.Appservers
	}
	return nil
}

type DeleteAppserverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppserverResponse) Reset() {
	*x = DeleteAppserverResponse{}
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppserverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppserverResponse) ProtoMessage() {}

func (x *DeleteAppserverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mistbe_v1_mistbe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppserverResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppserverResponse) Descriptor() ([]byte, []int) {
	return file_mistbe_v1_mistbe_proto_rawDescGZIP(), []int{8}
}

var File_mistbe_v1_mistbe_proto protoreflect.FileDescriptor

var file_mistbe_v1_mistbe_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x69, 0x73, 0x74, 0x62, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x73, 0x74,
	0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x69, 0x73, 0x74, 0x62, 0x65,
	0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x2c, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x29,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x15, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x30, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70,
	0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4d,
	0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x61, 0x70, 0x70,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d,
	0x69, 0x73, 0x74, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x09, 0x61, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x4e, 0x0a,
	0x18, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x61, 0x70, 0x70,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d,
	0x69, 0x73, 0x74, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x09, 0x61, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x4e, 0x0a,
	0x16, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x69,
	0x73, 0x74, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x22, 0x19, 0x0a,
	0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xff, 0x02, 0x0a, 0x0d, 0x4d, 0x69, 0x73,
	0x74, 0x42, 0x45, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x0f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x21, 0x2e,
	0x6d, 0x69, 0x73, 0x74, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x6d, 0x69, 0x73, 0x74, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49,
	0x64, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x6d, 0x69, 0x73,
	0x74, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x41, 0x70,
	0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23,
	0x2e, 0x6d, 0x69, 0x73, 0x74, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x49, 0x64, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70, 0x70,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x20, 0x2e, 0x6d, 0x69, 0x73, 0x74, 0x62, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6d, 0x69, 0x73, 0x74,
	0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a,
	0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x21, 0x2e, 0x6d, 0x69, 0x73, 0x74, 0x62, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x69, 0x73, 0x74, 0x62, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x6d,
	0x69, 0x73, 0x74, 0x62, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mistbe_v1_mistbe_proto_rawDescOnce sync.Once
	file_mistbe_v1_mistbe_proto_rawDescData = file_mistbe_v1_mistbe_proto_rawDesc
)

func file_mistbe_v1_mistbe_proto_rawDescGZIP() []byte {
	file_mistbe_v1_mistbe_proto_rawDescOnce.Do(func() {
		file_mistbe_v1_mistbe_proto_rawDescData = protoimpl.X.CompressGZIP(file_mistbe_v1_mistbe_proto_rawDescData)
	})
	return file_mistbe_v1_mistbe_proto_rawDescData
}

var file_mistbe_v1_mistbe_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mistbe_v1_mistbe_proto_goTypes = []any{
	(*Appserver)(nil),                // 0: mistbe.v1.Appserver
	(*CreateAppserverRequest)(nil),   // 1: mistbe.v1.CreateAppserverRequest
	(*GetByIdAppserverRequest)(nil),  // 2: mistbe.v1.GetByIdAppserverRequest
	(*ListAppserversRequest)(nil),    // 3: mistbe.v1.ListAppserversRequest
	(*DeleteAppserverRequest)(nil),   // 4: mistbe.v1.DeleteAppserverRequest
	(*CreateAppserverResponse)(nil),  // 5: mistbe.v1.CreateAppserverResponse
	(*GetByIdAppserverResponse)(nil), // 6: mistbe.v1.GetByIdAppserverResponse
	(*ListAppserversResponse)(nil),   // 7: mistbe.v1.ListAppserversResponse
	(*DeleteAppserverResponse)(nil),  // 8: mistbe.v1.DeleteAppserverResponse
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),   // 10: google.protobuf.StringValue
}
var file_mistbe_v1_mistbe_proto_depIdxs = []int32{
	9,  // 0: mistbe.v1.Appserver.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: mistbe.v1.ListAppserversRequest.name:type_name -> google.protobuf.StringValue
	0,  // 2: mistbe.v1.CreateAppserverResponse.appserver:type_name -> mistbe.v1.Appserver
	0,  // 3: mistbe.v1.GetByIdAppserverResponse.appserver:type_name -> mistbe.v1.Appserver
	0,  // 4: mistbe.v1.ListAppserversResponse.appservers:type_name -> mistbe.v1.Appserver
	1,  // 5: mistbe.v1.MistBEService.CreateAppserver:input_type -> mistbe.v1.CreateAppserverRequest
	2,  // 6: mistbe.v1.MistBEService.GetByIdAppserver:input_type -> mistbe.v1.GetByIdAppserverRequest
	3,  // 7: mistbe.v1.MistBEService.ListAppservers:input_type -> mistbe.v1.ListAppserversRequest
	4,  // 8: mistbe.v1.MistBEService.DeleteAppserver:input_type -> mistbe.v1.DeleteAppserverRequest
	5,  // 9: mistbe.v1.MistBEService.CreateAppserver:output_type -> mistbe.v1.CreateAppserverResponse
	6,  // 10: mistbe.v1.MistBEService.GetByIdAppserver:output_type -> mistbe.v1.GetByIdAppserverResponse
	7,  // 11: mistbe.v1.MistBEService.ListAppservers:output_type -> mistbe.v1.ListAppserversResponse
	8,  // 12: mistbe.v1.MistBEService.DeleteAppserver:output_type -> mistbe.v1.DeleteAppserverResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_mistbe_v1_mistbe_proto_init() }
func file_mistbe_v1_mistbe_proto_init() {
	if File_mistbe_v1_mistbe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mistbe_v1_mistbe_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mistbe_v1_mistbe_proto_goTypes,
		DependencyIndexes: file_mistbe_v1_mistbe_proto_depIdxs,
		MessageInfos:      file_mistbe_v1_mistbe_proto_msgTypes,
	}.Build()
	File_mistbe_v1_mistbe_proto = out.File
	file_mistbe_v1_mistbe_proto_rawDesc = nil
	file_mistbe_v1_mistbe_proto_goTypes = nil
	file_mistbe_v1_mistbe_proto_depIdxs = nil
}
